<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
//use PHPUnit\Framework\TestCase;
use App\Test\Product;
class ProductTest extends TestCase
{

    protected $product;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = new Product('fallout 4', 59);
    }

    /*public function a_product_has_a_name()
    {
        $product = new Product('fallout 4');
        $this->assertEquals('fallout 4', $product->name());
    }*/

    public function test_a_product_has_a_name()
    {
//        $product = new Product('fallout 4', 59);
        $this->assertEquals('fallout 4', $this->product->name());
    }

    public function test_a_product_has_a_price()
    {
//        $product = new Product('fallout 4', 59);
        $this->assertEquals('59', $this->product->price());
    }
}
